module.exports = {
  "beer": "while",
  "collatz": "角谷猜想",
  "collatz2": "考拉兹猜想（角谷猜想）",
  "divination": "春秋古筮法",
  "eightqueens": "八皇后問題",
  "euclidean": "歐幾里得法",
  "factorial": "階乘",
  "fibonacci": "斐波那契",
  "fibonacci2": "斐氏列",
  "fizzbuzz": "Fizz buzz",
  "hanoi": "漢諾塔",
  "helloworld": "問天地好在",
  "helloworld+": "問天地好在+",
  "import": "導入",
  "mandelbrot": "曼德博集",
  "mergesort": "歸併排序",
  "misc": "雜項",
  "modinv": "大衍求一術",
  "multiplication_table": "乘算口訣",
  "nested_fun": "函数",
  "obj": "对象",
  "pi_leibniz": "萊布尼茲圓周率估算",
  "quicksort": "快速排序",
  "quicksort_inplace": "快速排序2",
  "quine": "自產生程式",
  "quine2": "自產生程式2",
  "selectionsort": "選擇排序",
  "sieve": "埃氏篩",
  "sqrt_newton": "牛頓求根法",
  "turing": "圖靈機",
};
