const fs = require("fs");
const { examplesAlias, examplesLinks } = require("./examples_info");

const files = fs
  .readdirSync(__dirname + "/../examples/")
  .filter(x => x.endsWith(".wy"));
files.sort((a, b) => a.slice(0, -3).localeCompare(b.slice(0, -3)));

const leftWidth = "--------------------------------------".length;
const rightWidth = "-------------------------".length;

let content = `<!-- Auto generated. DO NOT edit this file manually. -->
# Examples（範例）

| File（文檔）                           | Remark（說明）            |
| -------------------------------------- | ------------------------- |
`;

function ansiLength(str) {
  return str.length + str.replace(/[\x00-\xff]+/g, "").length;
}

let links = [];

for (let fname of files) {
  let basename = fname.replace(/\.wy$/, "");
  let left = `[${fname}](${fname})`;
  if (left.length < leftWidth) {
    left = left.padEnd(leftWidth, " ");
  } else {
    left += " ";
  }
  let alias = examplesAlias[basename];
  let link = examplesLinks[basename];
  let linkTag = link && /^\[.+?\]:/.test(link) && link.match(/^\[.+?\]/)[0];
  let right = link ? `[${alias || basename}]${linkTag}` : alias || "";
  let rightLength = ansiLength(right);
  let d = leftWidth + rightWidth - left.length - rightLength;
  if (d >= 0) {
    right += " ".repeat(d);
  } else {
    right += " ";
  }
  if (link) {
    links.push(`${link}`);
  }
  content += `| ${left} | ${right} |` + "\n";
}

if (links.length) {
  content += "\n";
  content += links.join("\n");
  content += "\n";
}

console.log(content);

fs.writeFileSync(__dirname + "/../examples/README.md", content);

console.log('"examples/README.md" updated');
